"""Default business configuration for HeliAntha Smart Quote.

These values are provisional development defaults. They are kept outside the
templates, JavaScript and calculator formulas so HeliAntha can replace them
later from the admin/database layer without rebuilding the application.
"""

PROJECT_LABELS = {
    "pumping": "Pompage solaire",
    "offgrid": "Installation Off-Grid",
    "ongrid": "Installation On-Grid",
    "hybrid": "Installation hybride",
    "thermal": "Chauffage solaire",
    "ev": "Borne de recharge EV",
    "iot": "IoT / systemes embarques",
}

PUBLIC_PROJECTS = ("pumping", "offgrid", "ongrid", "hybrid", "thermal", "ev")

QUOTE_STATUSES = [
    "Nouveau",
    "A contacter",
    "Contacte",
    "Etude",
    "Visite programmee",
    "Devis prepare",
    "Devis envoye",
    "Accepte",
    "Refuse",
    "Installation",
    "Termine",
]

CALCULATOR_VERSIONS = {
    "SolarCalculator": "1.0",
    "PumpCalculator": "1.0",
    "OffGridCalculator": "1.0",
    "OnGridCalculator": "1.0",
    "HybridCalculator": "1.0",
    "SolarThermalCalculator": "1.0",
    "EVChargerCalculator": "1.0",
    "IoTCalculator": "0.5-hors-perimetre",
    "PricingEngine": "2.0-bom",
    "ProductSelector": "1.0",
    "CompatibilityChecker": "3.0",
    "BOMBuilder": "1.0",
}

TECHNICAL_REFERENCE = {
    "name": "MAROC-2026",
    "version": "1.0",
    "description": "Referentiel provisoire de developpement pour le marche marocain.",
    "effective_date": "2026-08-26",
    "status": "Actif",
    "notes": "A remplacer par le referentiel technique valide par HeliAntha.",
}

COMPANY_SETTINGS = [
    ("company_name", "HELIANTHA", "general", "Nom entreprise"),
    ("phone", "05 30 13 35 83", "contact", "Telephone fixe"),
    ("whatsapp", "+212 661-575128", "contact", "WhatsApp"),
    ("email", "contact@heliantha.ma", "contact", "E-mail"),
    ("address", "Maroc", "contact", "Adresse"),
    ("website", "www.heliantha.ma", "contact", "Site internet"),
    ("location_url", "https://maps.app.goo.gl/xAfGJugGUMye8oSX7", "contact", "Localisation Google Maps"),
    ("quote_validity_days", "15", "quote", "Duree de validite devis"),
    ("currency", "DH", "quote", "Devise"),
    ("pdf_footer", "Pre-devis soumis a validation technique HeliAntha.", "quote", "Texte PDF"),
]

CALCULATION_PARAMETERS = [
    ("pv_panel_default_w", "Puissance panneau par defaut", 590, "W", "Photovoltaique", "Puissance de reference si aucun produit catalogue n'est disponible."),
    ("pv_performance_ratio", "Productible/performance PV", 0.80, "ratio", "Photovoltaique", "Rendement global provisoire du champ PV."),
    ("pv_losses", "Pertes PV", 0.15, "ratio", "Photovoltaique", "Pertes cables, temperature, poussiere et conversion."),
    ("pv_safety_margin", "Marge de dimensionnement PV", 0.15, "ratio", "Photovoltaique", "Marge technique provisoire appliquee au besoin PV."),
    ("pv_dc_ac_ratio_min", "Ratio DC/AC minimal de controle", 0.80, "coefficient", "Photovoltaique", "Limite basse provisoire du controle de coherence entre champ PV et onduleur."),
    ("pv_dc_ac_ratio_max", "Ratio DC/AC maximal de controle", 1.30, "coefficient", "Photovoltaique", "Limite haute provisoire du controle de coherence entre champ PV et onduleur."),
    ("productible_default_psh", "Ensoleillement par defaut", 5.4, "h/j", "Photovoltaique", "Heures solaires equivalentes utilisees hors ville referencee."),
    ("battery_dod", "Profondeur de decharge batterie", 0.80, "ratio", "Batteries", "DOD provisoire pour batteries lithium."),
    ("battery_efficiency", "Rendement batterie", 0.93, "ratio", "Batteries", "Rendement charge/decharge provisoire."),
    ("battery_capacity_margin", "Marge capacite batterie", 0.10, "ratio", "Batteries", "Marge de securite capacite."),
    ("autonomy_default_days", "Autonomie par defaut", 1.0, "jour", "Batteries", "Autonomie par defaut si non renseignee."),
    ("inverter_peak_factor", "Coefficient puissance onduleur", 1.25, "ratio", "Onduleur", "Marge sur puissance simultanee maximale."),
    ("inverter_efficiency", "Rendement onduleur", 0.96, "ratio", "Onduleur", "Rendement provisoire onduleur."),
    ("water_density", "Densite eau", 1000, "kg/m3", "Pompage", "Densite de l'eau."),
    ("gravity", "Gravite", 9.81, "m/s2", "Pompage", "Acceleration gravitationnelle."),
    ("ev_charge_efficiency", "Rendement recharge EV", 0.90, "ratio", "Borne EV", "Rendement de recharge AC provisoire."),
    ("ev_safety_factor", "Securite borne EV", 0.10, "ratio", "Borne EV", "Marge sur puissance disponible."),
    ("thermal_liters_per_person", "Besoin ECS par personne", 50, "L/j", "Thermique", "Besoin journalier provisoire en eau chaude sanitaire."),
    ("thermal_inlet_temp", "Temperature eau froide", 15, "degC", "Thermique", "Temperature d'entree estimee."),
    ("thermal_target_temp", "Temperature ECS souhaitee", 55, "degC", "Thermique", "Temperature cible estimee."),
    ("thermal_losses", "Pertes thermiques", 0.20, "ratio", "Thermique", "Pertes systeme provisoires."),
    ("thermal_collector_liters", "Capacite par capteur", 150, "L", "Thermique", "Capacite ballon couverte par capteur."),
]

SOURCE_TYPES = {
    "demo": {"label": "HeliAntha", "badge": "✅ HeliAntha", "description": "Valeur HeliAntha utilisée pour les simulations."},
    "heliantha": {"label": "HeliAntha", "badge": "✅ HeliAntha", "description": "Valeur validée par HeliAntha."},
    "manufacturer": {"label": "Fabricant", "badge": "🏭 Fabricant", "description": "Donnée issue d'une fiche technique constructeur."},
    "reference": {"label": "Référentiel", "badge": "📚 Référentiel", "description": "Donnée issue d'un référentiel technique."},
    "physical_constant": {"label": "Constante physique", "badge": "🔬 Constante physique", "description": "Valeur scientifique normalement verrouillée."},
    "local_data": {"label": "Donnée locale", "badge": "📍 Donnée locale", "description": "Donnée liée à une ville, une région ou une mesure locale."},
}

CATEGORY_PRESENTATION = {
    "Photovoltaique": {"label": "Photovoltaïque", "icon": "☀️", "order": 10},
    "Batteries": {"label": "Batteries", "icon": "🔋", "order": 20},
    "Onduleur": {"label": "Onduleurs", "icon": "⚡", "order": 30},
    "Pompage": {"label": "Pompage", "icon": "💧", "order": 40},
    "Borne EV": {"label": "Bornes EV", "icon": "🚗", "order": 50},
    "Thermique": {"label": "Thermique", "icon": "♨️", "order": 60},
}

PARAMETER_PRESENTATION = {
    "autonomy_default_days": {
        "display_name": "Autonomie batterie par défaut",
        "display_kind": "duration_days",
        "plain_explanation": "Si le client ne précise pas l'autonomie souhaitée, le système utilise cette durée pour effectuer son estimation.",
        "used_for": "Dimensionnement des batteries pour les systèmes Off-Grid et hybrides.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "OffGridCalculator, HybridCalculator",
    },
    "battery_capacity_margin": {
        "display_name": "Marge de sécurité batterie",
        "display_kind": "percent",
        "plain_explanation": "Une marge supplémentaire est ajoutée à la capacité de batterie calculée afin d'éviter un dimensionnement trop juste.",
        "used_for": "Dimensionner la capacité nécessaire des batteries.",
        "example": "Si le besoin calculé est de 10 kWh, une marge de 10 % conduit à prévoir environ 11 kWh.",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "OffGridCalculator, HybridCalculator",
    },
    "battery_dod": {
        "display_name": "Part utilisable de la batterie (DoD)",
        "display_kind": "percent",
        "plain_explanation": "Une batterie n'est généralement pas dimensionnée en considérant que 100 % de sa capacité sera utilisée. Avec 80 %, une batterie de 10 kWh fournit environ 8 kWh considérés comme utilisables dans le calcul.",
        "used_for": "Calculer la capacité batterie nominale à prévoir.",
        "example": "Batterie nominale : 10 kWh. Capacité considérée comme utilisable : environ 8 kWh.",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "OffGridCalculator, HybridCalculator",
    },
    "battery_efficiency": {
        "display_name": "Rendement de la batterie",
        "display_kind": "percent",
        "plain_explanation": "Une petite partie de l'énergie est perdue pendant la charge et la décharge. Le calcul estime ici que 93 % de l'énergie est réellement récupérable.",
        "used_for": "Dimensionnement du stockage batterie.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "OffGridCalculator, HybridCalculator",
    },
    "ev_charge_efficiency": {
        "display_name": "Rendement de recharge du véhicule",
        "display_kind": "percent",
        "plain_explanation": "Toute l'énergie prélevée sur l'installation électrique n'arrive pas dans la batterie du véhicule. Une partie est perdue pendant la recharge.",
        "used_for": "Estimer la durée de recharge et l'énergie utile transférée au véhicule.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "EVChargerCalculator",
    },
    "ev_safety_factor": {
        "display_name": "Marge de sécurité pour borne EV",
        "display_kind": "percent",
        "plain_explanation": "Marge utilisée pour éviter de dimensionner l'alimentation électrique exactement à sa limite.",
        "used_for": "Préparer le contrôle de cohérence de la puissance disponible pour une borne EV.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "EVChargerCalculator",
    },
    "inverter_efficiency": {
        "display_name": "Rendement de l'onduleur",
        "display_kind": "percent",
        "plain_explanation": "L'onduleur transforme l'électricité mais une petite partie de l'énergie est perdue pendant cette conversion.",
        "used_for": "Préparer les calculs liés aux conversions électriques et aux futurs choix produit.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "SolarCalculator, OffGridCalculator, HybridCalculator, OnGridCalculator",
    },
    "inverter_peak_factor": {
        "display_name": "Marge de puissance de l'onduleur",
        "display_kind": "multiplier_margin",
        "plain_explanation": "L'onduleur est dimensionné avec une marge au-dessus de la puissance simultanée estimée des équipements.",
        "used_for": "Choisir la puissance minimale de l'onduleur.",
        "example": "Puissance calculée : 4 kW. Avec une marge de 25 %, on vise environ 5 kW.",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "OffGridCalculator, HybridCalculator",
    },
    "productible_default_psh": {
        "display_name": "Ensoleillement solaire utilisé par défaut",
        "display_kind": "psh",
        "plain_explanation": "Cette valeur représente le nombre approximatif d'heures par jour pendant lesquelles l'ensoleillement correspondrait à une production solaire maximale équivalente. Elle doit être remplacée par une donnée adaptée à la localisation lorsque celle-ci est disponible.",
        "used_for": "Calculer la puissance photovoltaïque nécessaire lorsqu'aucune ville connue n'est disponible.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse géographique provisoire",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "SolarCalculator, PumpCalculator, OffGridCalculator, OnGridCalculator, HybridCalculator",
    },
    "pv_losses": {
        "display_name": "Pertes estimées de l'installation photovoltaïque",
        "display_kind": "percent",
        "plain_explanation": "Le système prévoit une partie de l'énergie perdue à cause notamment de la température, des câbles, de la poussière et des conversions électriques.",
        "used_for": "Corriger le besoin énergétique avant dimensionnement photovoltaïque.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "OffGridCalculator, HybridCalculator",
    },
    "pv_panel_default_w": {
        "display_name": "Puissance du panneau utilisée par défaut",
        "display_kind": "power_w",
        "plain_explanation": "Si aucun panneau compatible n'est trouvé ou sélectionné dans le catalogue, cette puissance sert de référence provisoire au calcul. Le catalogue HeliAntha doit être utilisé en priorité lorsqu'un produit adapté est disponible.",
        "used_for": "Calculer le nombre de panneaux lorsqu'aucun produit catalogue exploitable n'est disponible.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "SolarCalculator, PumpCalculator, OffGridCalculator, OnGridCalculator, HybridCalculator",
    },
    "pv_performance_ratio": {
        "display_name": "Performance globale estimée du système photovoltaïque",
        "display_kind": "percent",
        "plain_explanation": "Ce coefficient représente la performance globale estimée du champ photovoltaïque après prise en compte de différentes pertes du système.",
        "used_for": "Calculer la puissance photovoltaïque nécessaire à partir d'un besoin énergétique.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "SolarCalculator, PumpCalculator, OffGridCalculator, OnGridCalculator, HybridCalculator",
    },
    "pv_safety_margin": {
        "display_name": "Marge de dimensionnement photovoltaïque",
        "display_kind": "percent",
        "plain_explanation": "Le système ajoute une marge à la puissance photovoltaïque calculée afin d'éviter une installation dimensionnée trop juste.",
        "used_for": "Préparer une puissance photovoltaïque avec réserve technique.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "SolarCalculator",
    },
    "gravity": {
        "display_name": "Gravité terrestre",
        "display_kind": "gravity",
        "plain_explanation": "Constante physique utilisée dans certains calculs de pompage hydraulique.",
        "used_for": "Calculer la puissance hydraulique d'un projet de pompage.",
        "example": "",
        "source_type": "physical_constant",
        "source_name": "Constante physique",
        "source_reference": "g = 9,81 m/s²",
        "validated_by": "",
        "validated_at": "",
        "editable": False,
        "calculator_usage": "PumpCalculator",
    },
    "pump_drive_efficiency": {
        "display_name": "Rendement du variateur de pompage",
        "display_kind": "percent",
        "plain_explanation": "Une partie de l'énergie est perdue lors de la conversion effectuée par le variateur qui alimente la pompe.",
        "used_for": "Calculer la puissance électrique nécessaire au pompage.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "PumpCalculator",
    },
    "pump_efficiency": {
        "display_name": "Rendement estimé de la pompe",
        "display_kind": "percent",
        "plain_explanation": "Ce rendement représente la part de l'énergie électrique transformée efficacement en énergie hydraulique. Le rendement réel dépend de la pompe et de son point de fonctionnement.",
        "used_for": "Calculer la puissance de pompe nécessaire depuis le besoin hydraulique.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "PumpCalculator",
    },
    "pump_hydraulic_losses_rate": {
        "display_name": "Pertes hydrauliques estimées",
        "display_kind": "percent",
        "plain_explanation": "Le calcul ajoute une estimation des pertes dues notamment aux canalisations, raccords, coudes et autres résistances du circuit hydraulique.",
        "used_for": "Calculer la hauteur manométrique totale d'un projet de pompage.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "PumpCalculator",
    },
    "pump_safety_factor": {
        "display_name": "Marge de sécurité pompage",
        "display_kind": "percent",
        "plain_explanation": "Le calcul ajoute une marge pour éviter que la pompe et le champ solaire soient dimensionnés trop juste.",
        "used_for": "Dimensionner la pompe et la puissance photovoltaïque de pompage.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "PumpCalculator",
    },
    "water_density": {
        "display_name": "Densité de l'eau",
        "display_kind": "density",
        "plain_explanation": "Constante utilisée pour convertir un débit et une hauteur d'eau en puissance hydraulique.",
        "used_for": "Calculer la puissance hydraulique d'un projet de pompage.",
        "example": "",
        "source_type": "physical_constant",
        "source_name": "Constante physique",
        "source_reference": "Eau douce ≈ 1 000 kg/m³",
        "validated_by": "",
        "validated_at": "",
        "editable": False,
        "calculator_usage": "PumpCalculator",
    },
    "thermal_liters_per_person": {
        "display_name": "Besoin d'eau chaude par personne",
        "display_kind": "liters_per_day",
        "plain_explanation": "Volume d'eau chaude sanitaire estimé par personne et par jour quand le client ne fournit pas un besoin détaillé.",
        "used_for": "Dimensionner le ballon et les capteurs solaires thermiques.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "SolarThermalCalculator",
    },
    "thermal_inlet_temp": {
        "display_name": "Température estimée de l'eau froide",
        "display_kind": "temperature",
        "plain_explanation": "Température d'entrée utilisée pour estimer l'énergie nécessaire au chauffage de l'eau.",
        "used_for": "Calculer le besoin thermique journalier.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "SolarThermalCalculator",
    },
    "thermal_target_temp": {
        "display_name": "Température d'eau chaude souhaitée",
        "display_kind": "temperature",
        "plain_explanation": "Température cible utilisée pour estimer l'énergie nécessaire au chauffage de l'eau.",
        "used_for": "Calculer le besoin thermique journalier.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "SolarThermalCalculator",
    },
    "thermal_losses": {
        "display_name": "Pertes thermiques estimées",
        "display_kind": "percent",
        "plain_explanation": "Marge de pertes utilisée pour tenir compte des pertes du système solaire thermique.",
        "used_for": "Corriger le besoin thermique avant sélection du ballon et des capteurs.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "SolarThermalCalculator",
    },
    "thermal_collector_liters": {
        "display_name": "Capacité couverte par capteur thermique",
        "display_kind": "liters",
        "plain_explanation": "Volume de ballon considéré comme couvert par un capteur solaire thermique dans l'estimation provisoire.",
        "used_for": "Calculer le nombre de capteurs solaires thermiques.",
        "example": "",
        "source_type": "demo",
        "source_name": "Hypothèse provisoire de développement",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "SolarThermalCalculator",
    },
}

PARAMETER_PRESENTATION.update({
    "pv_dc_ac_ratio_min": {
        "display_name": "Ratio champ PV / onduleur - limite basse",
        "display_kind": "coefficient",
        "plain_explanation": "Ce seuil provisoire sert uniquement à contrôler que la puissance continue du champ photovoltaïque reste cohérente avec la puissance alternative de l'onduleur.",
        "used_for": "Contrôler la cohérence DC/AC lors de la sélection catalogue de l'onduleur.",
        "example": "Un ratio de 1,08 signifie 6,49 kWp de panneaux pour un onduleur de 6 kW.",
        "source_type": "demo",
        "source_name": "Plage de contrôle provisoire",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "ProductSelector, CompatibilityChecker",
    },
    "pv_dc_ac_ratio_max": {
        "display_name": "Ratio champ PV / onduleur - limite haute",
        "display_kind": "coefficient",
        "plain_explanation": "Ce seuil provisoire évite de valider automatiquement un champ photovoltaïque trop important par rapport à l'onduleur. Il devra être validé par HeliAntha.",
        "used_for": "Contrôler la cohérence DC/AC lors de la sélection catalogue de l'onduleur.",
        "example": "La valeur ne constitue pas encore une règle officielle HeliAntha.",
        "source_type": "demo",
        "source_name": "Plage de contrôle provisoire",
        "source_reference": "",
        "validated_by": "",
        "validated_at": "",
        "editable": True,
        "calculator_usage": "ProductSelector, CompatibilityChecker",
    },
    "battery_dod": {
        **PARAMETER_PRESENTATION["battery_dod"],
        "display_name": "Part utilisable par defaut de la batterie",
        "plain_explanation": "Cette valeur de secours est utilisee lorsqu'aucune batterie selectionnee ne fournit une information plus precise. Une batterie de 10 kWh est alors consideree comme offrant environ 8 kWh utilisables dans le calcul.",
        "used_for": "Servir de valeur de secours pour le dimensionnement des batteries Off-Grid et hybrides.",
    },
    "battery_efficiency": {
        **PARAMETER_PRESENTATION["battery_efficiency"],
        "display_name": "Rendement batterie par defaut",
        "plain_explanation": "Cette valeur de secours represente l'energie recuperee apres charge et decharge lorsqu'aucune batterie selectionnee ne fournit de rendement plus precis.",
        "used_for": "Servir de valeur de secours pour le calcul du stockage batterie.",
    },
    "inverter_efficiency": {
        **PARAMETER_PRESENTATION["inverter_efficiency"],
        "display_name": "Rendement onduleur par defaut",
        "plain_explanation": "Cette valeur de secours est conservee pour une future methode distinguant explicitement certaines conversions electriques. Elle n'est pas appliquee separement dans la formule provisoire actuelle afin d'eviter un double comptage possible avec la performance globale PV.",
        "used_for": "Conserve pour une evolution future, sans effet direct dans la formule actuelle.",
        "calculator_usage": "Conserve pour evolution future - non utilise actuellement",
    },
    "productible_default_psh": {
        **PARAMETER_PRESENTATION["productible_default_psh"],
        "display_name": "Ensoleillement utilise en secours",
        "plain_explanation": "Cette valeur est utilisee seulement lorsqu'aucune donnee locale plus adaptee n'est disponible pour la ville ou la zone du projet. Elle ne doit pas etre comprise comme une valeur valable partout au Maroc.",
        "used_for": "Servir de valeur de secours quand aucune donnee locale d'ensoleillement n'est disponible.",
        "source_name": "Valeur de secours de developpement",
    },
    "pv_losses": {
        **PARAMETER_PRESENTATION["pv_losses"],
        "display_name": "Pertes PV detaillees - non utilisees dans la formule actuelle",
        "plain_explanation": "Le moteur utilise actuellement le Performance Ratio comme correction globale photovoltaïque. Ce parametre est conserve pour compatibilite et pourra etre reactive plus tard si HeliAntha adopte une methode separant precisement les pertes.",
        "used_for": "Reserve a une methode future separant les pertes photovoltaïques.",
        "calculator_usage": "Conserve pour evolution future - non utilise actuellement",
    },
    "pv_panel_default_w": {
        **PARAMETER_PRESENTATION["pv_panel_default_w"],
        "display_name": "Puissance panneau de secours",
        "plain_explanation": "Utilisee uniquement lorsqu'aucun panneau compatible n'est disponible ou selectionne dans le catalogue. Le catalogue HeliAntha reste prioritaire.",
        "used_for": "Servir de valeur de secours pour le calcul du nombre de panneaux.",
    },
    "pv_safety_margin": {
        **PARAMETER_PRESENTATION["pv_safety_margin"],
        "calculator_usage": "PumpCalculator, OffGridCalculator, OnGridCalculator, HybridCalculator",
    },
    "pump_drive_efficiency": {
        **PARAMETER_PRESENTATION["pump_drive_efficiency"],
        "display_name": "Rendement variateur par defaut",
        "plain_explanation": "Cette valeur de secours represente les pertes du variateur de pompage lorsqu'aucune fiche produit plus precise n'est disponible.",
        "used_for": "Servir de valeur de secours pour estimer la puissance electrique necessaire au pompage.",
    },
    "pump_efficiency": {
        **PARAMETER_PRESENTATION["pump_efficiency"],
        "display_name": "Rendement pompe par defaut",
        "plain_explanation": "Cette valeur de secours represente la part de l'energie electrique transformee en energie hydraulique lorsqu'aucune pompe selectionnee ne fournit de rendement reel.",
        "used_for": "Servir de valeur de secours pour calculer la puissance de pompe.",
    },
    "ev_charge_efficiency": {
        **PARAMETER_PRESENTATION["ev_charge_efficiency"],
        "display_name": "Rendement de recharge par defaut",
        "plain_explanation": "Cette valeur de secours tient compte des pertes de recharge lorsqu'aucune information plus precise n'est disponible sur le materiel ou le vehicule.",
        "used_for": "Servir de valeur de secours pour estimer la recharge EV.",
    },
    "thermal_inlet_temp": {
        **PARAMETER_PRESENTATION["thermal_inlet_temp"],
        "display_name": "Temperature d'eau froide utilisee par defaut",
        "plain_explanation": "Cette temperature d'entree sert de secours lorsqu'aucune donnee locale ou mesure du site n'est disponible.",
        "used_for": "Servir de valeur de secours pour le calcul thermique.",
    },
    "thermal_collector_liters": {
        **PARAMETER_PRESENTATION["thermal_collector_liters"],
        "display_name": "Valeur capteur thermique de secours",
        "plain_explanation": "Cette valeur provisoire sert de secours pour estimer le nombre de capteurs. Elle devra idealement etre remplacee par une caracteristique reelle du systeme ou du capteur catalogue.",
        "used_for": "Servir de valeur de secours pour estimer la couverture d'un capteur thermique.",
    },
    "gravity": {
        **PARAMETER_PRESENTATION["gravity"],
        "source_name": "Code uniquement",
    },
    "water_density": {
        **PARAMETER_PRESENTATION["water_density"],
        "source_name": "Code uniquement",
    },
})

PARAMETER_CLASSIFICATION = {
    "pv_dc_ac_ratio_min": {
        "management_scope": "business_rule",
        "role_label": "Contrôle provisoire",
        "role_description": "Limite configurable à faire valider par HeliAntha.",
        "admin_visible": True,
    },
    "pv_dc_ac_ratio_max": {
        "management_scope": "business_rule",
        "role_label": "Contrôle provisoire",
        "role_description": "Limite configurable à faire valider par HeliAntha.",
        "admin_visible": True,
    },
    "pv_safety_margin": {
        "management_scope": "business_rule",
        "role_label": "Regle HeliAntha",
        "role_description": "Marge metier configurable par HeliAntha.",
        "admin_visible": True,
    },
    "pv_losses": {
        "management_scope": "legacy",
        "role_label": "Heritage",
        "role_description": "Conserve pour compatibilite historique. Non affiche dans l'administration.",
        "admin_visible": False,
    },
    "pv_performance_ratio": {
        "management_scope": "fallback_rule",
        "role_label": "Valeur de secours",
        "role_description": "Performance globale utilisee lorsqu'aucune donnee plus specifique n'est disponible.",
        "admin_visible": True,
    },
    "productible_default_psh": {
        "management_scope": "fallback_local",
        "role_label": "Secours localisation",
        "role_description": "Donnée utilisee seulement en absence de donnee locale.",
        "admin_visible": True,
    },
    "pv_panel_default_w": {
        "management_scope": "fallback_product",
        "role_label": "Secours catalogue",
        "role_description": "Valeur utilisee seulement en absence de produit compatible.",
        "admin_visible": True,
    },
    "autonomy_default_days": {
        "management_scope": "business_rule",
        "role_label": "Regle HeliAntha",
        "role_description": "Duree par defaut choisie par HeliAntha.",
        "admin_visible": True,
    },
    "battery_capacity_margin": {
        "management_scope": "business_rule",
        "role_label": "Regle HeliAntha",
        "role_description": "Marge metier appliquee au dimensionnement batterie.",
        "admin_visible": True,
    },
    "battery_dod": {
        "management_scope": "fallback_product",
        "role_label": "Secours catalogue",
        "role_description": "Valeur de secours tant qu'aucune batterie selectionnee n'apporte une valeur reelle.",
        "admin_visible": True,
    },
    "battery_efficiency": {
        "management_scope": "fallback_product",
        "role_label": "Secours catalogue",
        "role_description": "Valeur de secours tant qu'aucune batterie selectionnee n'apporte un rendement reel.",
        "admin_visible": True,
    },
    "inverter_peak_factor": {
        "management_scope": "business_rule",
        "role_label": "Regle HeliAntha",
        "role_description": "Marge metier appliquee au choix d'onduleur.",
        "admin_visible": True,
    },
    "inverter_efficiency": {
        "management_scope": "legacy",
        "role_label": "Heritage",
        "role_description": "Conserve pour compatibilite historique. Non affiche dans l'administration.",
        "admin_visible": False,
    },
    "pump_safety_factor": {
        "management_scope": "business_rule",
        "role_label": "Regle HeliAntha",
        "role_description": "Marge metier de securite pour le pompage.",
        "admin_visible": True,
    },
    "pump_hydraulic_losses_rate": {
        "management_scope": "business_rule",
        "role_label": "Regle HeliAntha",
        "role_description": "Perte hydraulique estimee configurable par HeliAntha.",
        "admin_visible": True,
    },
    "pump_drive_efficiency": {
        "management_scope": "fallback_product",
        "role_label": "Secours catalogue",
        "role_description": "Valeur de secours tant qu'aucun variateur selectionne n'apporte un rendement reel.",
        "admin_visible": True,
    },
    "pump_efficiency": {
        "management_scope": "fallback_product",
        "role_label": "Secours catalogue",
        "role_description": "Valeur de secours tant qu'aucune pompe selectionnee n'apporte un rendement reel.",
        "admin_visible": True,
    },
    "ev_safety_factor": {
        "management_scope": "business_rule",
        "role_label": "Regle HeliAntha",
        "role_description": "Marge metier pour la borne EV.",
        "admin_visible": True,
    },
    "ev_charge_efficiency": {
        "management_scope": "fallback_product",
        "role_label": "Secours materiel",
        "role_description": "Valeur de secours tant qu'aucune information materielle plus precise n'est disponible.",
        "admin_visible": True,
    },
    "thermal_liters_per_person": {
        "management_scope": "business_rule",
        "role_label": "Regle HeliAntha",
        "role_description": "Besoin ECS par personne choisi par HeliAntha.",
        "admin_visible": True,
    },
    "thermal_losses": {
        "management_scope": "business_rule",
        "role_label": "Regle HeliAntha",
        "role_description": "Pertes thermiques estimees configurables.",
        "admin_visible": True,
    },
    "thermal_target_temp": {
        "management_scope": "business_rule",
        "role_label": "Regle HeliAntha",
        "role_description": "Temperature cible choisie par HeliAntha.",
        "admin_visible": True,
    },
    "thermal_inlet_temp": {
        "management_scope": "fallback_local",
        "role_label": "Secours localisation",
        "role_description": "Valeur de secours si aucune donnee locale du site n'est disponible.",
        "admin_visible": True,
    },
    "thermal_collector_liters": {
        "management_scope": "fallback_product",
        "role_label": "Secours catalogue",
        "role_description": "Valeur de secours en attendant une caracteristique reelle de systeme ou capteur catalogue.",
        "admin_visible": True,
    },
    "gravity": {
        "management_scope": "scientific_constant",
        "role_label": "Constante scientifique",
        "role_description": "Constante scientifique geree uniquement dans le code.",
        "admin_visible": False,
    },
    "water_density": {
        "management_scope": "scientific_constant",
        "role_label": "Constante scientifique",
        "role_description": "Constante scientifique geree uniquement dans le code.",
        "admin_visible": False,
    },
}

PARAMETER_ENGINE_USAGE = {
    "pv_dc_ac_ratio_min": {
        "status": "used",
        "badge": "✅ Utilise par le moteur",
        "note": "Utilisé comme limite basse provisoire du contrôle DC/AC lors du choix de l'onduleur réseau.",
    },
    "pv_dc_ac_ratio_max": {
        "status": "used",
        "badge": "✅ Utilise par le moteur",
        "note": "Utilisé comme limite haute provisoire du contrôle DC/AC lors du choix de l'onduleur réseau.",
    },
    "pv_losses": {
        "status": "unused",
        "badge": "ℹ️ Non utilise actuellement",
        "note": "Conserve pour compatibilite. La formule provisoire utilise le Performance Ratio comme correction globale PV.",
    },
    "inverter_efficiency": {
        "status": "unused",
        "badge": "ℹ️ Non utilise actuellement",
        "note": "Conserve pour une future methode de conversion distincte. Non applique separement dans la formule provisoire actuelle.",
    },
    "pv_safety_margin": {
        "status": "used",
        "badge": "✅ Utilise par le moteur",
        "note": "Applique une seule fois apres la puissance PV theorique pour definir la puissance PV cible.",
    },
    "ev_safety_factor": {
        "status": "used",
        "badge": "✅ Utilise par le moteur",
        "note": "Utilise pour verifier la puissance disponible recommandee autour de la borne retenue.",
    },
}

PRICING_RULES = [
    ("vat_rate", "TVA", 0.20, "rate", "ratio", None),
    ("accessories_rate", "Accessoires proportionnels", 0.06, "rate", "ratio", None),
    ("protections_rate", "Protections proportionnelles", 0.07, "rate", "ratio", None),
    ("cabling_rate", "Cablage proportionnel", 0.05, "rate", "ratio", None),
    ("structure_rate", "Structure proportionnelle", 0.08, "rate", "ratio", None),
    ("installation_base", "Installation de base", 2500, "fixed", "DH", None),
    ("labor_base", "Main-d'oeuvre de base", 2200, "fixed", "DH", None),
    ("commissioning_fee", "Mise en service", 800, "fixed", "DH", None),
]

CATALOG_PRODUCTS = [
    {
        "reference": "PV-590-HS",
        "category": "panels",
        "subcategory": "monocristallin",
        "brand": "HeliAntha Select",
        "model": "590 Wc",
        "description": "Panneau photovoltaique monocristallin 590 Wc.",
        "power_w": 590,
        "efficiency": 0.21,
        "sale_price": 1100,
        "unit": "piece",
        "warranty": "12 ans produit",
        "technical_specs": {"surface_m2": 2.6},
    },
    {
        "reference": "PV-550-HS",
        "category": "panels",
        "subcategory": "monocristallin",
        "brand": "HeliAntha Select",
        "model": "550 Wc",
        "description": "Panneau photovoltaique monocristallin 550 Wc.",
        "power_w": 550,
        "efficiency": 0.205,
        "sale_price": 980,
        "unit": "piece",
        "warranty": "12 ans produit",
        "technical_specs": {"surface_m2": 2.45},
    },
    {
        "reference": "BAT-LFP-5",
        "category": "batteries",
        "subcategory": "lithium",
        "brand": "HeliAntha Storage",
        "model": "LFP 5.12 kWh",
        "description": "Module batterie lithium LFP.",
        "capacity_kwh": 5.12,
        "voltage": 51.2,
        "technology": "LiFePO4",
        "sale_price": 16800,
        "unit": "piece",
        "warranty": "5 ans",
    },
    {
        "reference": "BAT-LFP-10",
        "category": "batteries",
        "subcategory": "lithium",
        "brand": "HeliAntha Storage",
        "model": "LFP 10.24 kWh",
        "description": "Module batterie lithium LFP haute capacite.",
        "capacity_kwh": 10.24,
        "voltage": 51.2,
        "technology": "LiFePO4",
        "sale_price": 31800,
        "unit": "piece",
        "warranty": "5 ans",
    },
    {
        "reference": "INV-GRID-5",
        "category": "inverters",
        "subcategory": "on-grid",
        "brand": "HeliAntha Power",
        "model": "Grid 5 kW",
        "description": "Onduleur reseau 5 kW.",
        "power_kw": 5,
        "efficiency": 0.97,
        "sale_price": 8500,
        "unit": "piece",
        "warranty": "5 ans",
    },
    {
        "reference": "INV-GRID-10",
        "category": "inverters",
        "subcategory": "on-grid",
        "brand": "HeliAntha Power",
        "model": "Grid 10 kW",
        "description": "Onduleur reseau 10 kW.",
        "power_kw": 10,
        "efficiency": 0.97,
        "sale_price": 14500,
        "unit": "piece",
        "warranty": "5 ans",
    },
    {
        "reference": "INV-HYB-5",
        "category": "inverters",
        "subcategory": "hybride",
        "brand": "HeliAntha Power",
        "model": "Hybrid 5 kW",
        "description": "Onduleur hybride 5 kW.",
        "power_kw": 5,
        "efficiency": 0.96,
        "sale_price": 12200,
        "unit": "piece",
        "warranty": "5 ans",
    },
    {
        "reference": "INV-HYB-8",
        "category": "inverters",
        "subcategory": "hybride",
        "brand": "HeliAntha Power",
        "model": "Hybrid 8 kW",
        "description": "Onduleur hybride 8 kW.",
        "power_kw": 8,
        "efficiency": 0.96,
        "sale_price": 17800,
        "unit": "piece",
        "warranty": "5 ans",
    },
    {
        "reference": "PUMP-2.2",
        "category": "pumps",
        "subcategory": "immergee",
        "brand": "HeliAntha Pump",
        "model": "Solar Pump 2.2 kW",
        "description": "Pompe immergee solaire.",
        "power_kw": 2.2,
        "sale_price": 9200,
        "unit": "piece",
    },
    {
        "reference": "PUMP-4.0",
        "category": "pumps",
        "subcategory": "immergee",
        "brand": "HeliAntha Pump",
        "model": "Solar Pump 4 kW",
        "description": "Pompe immergee solaire.",
        "power_kw": 4,
        "sale_price": 14800,
        "unit": "piece",
    },
    {
        "reference": "DRV-4.0",
        "category": "drives",
        "subcategory": "variateur solaire",
        "brand": "HeliAntha Drive",
        "model": "Solar Drive 4 kW",
        "description": "Variateur solaire pour pompe.",
        "power_kw": 4,
        "sale_price": 6900,
        "unit": "piece",
    },
    {
        "reference": "EV-7.4",
        "category": "ev_chargers",
        "subcategory": "monophase",
        "brand": "HeliAntha Charge",
        "model": "AC 7.4 kW",
        "description": "Borne de recharge AC monophasée.",
        "power_kw": 7.4,
        "current_amp": 32,
        "sale_price": 9200,
        "unit": "piece",
        "technical_specs": {"phases": "monophase", "connector": "Type 2"},
    },
    {
        "reference": "EV-11",
        "category": "ev_chargers",
        "subcategory": "triphase",
        "brand": "HeliAntha Charge",
        "model": "AC 11 kW",
        "description": "Borne de recharge AC triphasée.",
        "power_kw": 11,
        "current_amp": 16,
        "sale_price": 11800,
        "unit": "piece",
        "technical_specs": {"phases": "triphase", "connector": "Type 2"},
    },
    {
        "reference": "EV-22",
        "category": "ev_chargers",
        "subcategory": "triphase",
        "brand": "HeliAntha Charge",
        "model": "AC 22 kW",
        "description": "Borne de recharge AC triphasée.",
        "power_kw": 22,
        "current_amp": 32,
        "sale_price": 15800,
        "unit": "piece",
        "technical_specs": {"phases": "triphase", "connector": "Type 2"},
    },
    {
        "reference": "THERM-200",
        "category": "thermal",
        "subcategory": "ballon solaire",
        "brand": "HeliAntha Therm",
        "model": "Ballon 200 L",
        "description": "Ballon solaire equipe.",
        "capacity_l": 200,
        "sale_price": 7600,
        "unit": "piece",
    },
    {
        "reference": "THERM-300",
        "category": "thermal",
        "subcategory": "ballon solaire",
        "brand": "HeliAntha Therm",
        "model": "Ballon 300 L",
        "description": "Ballon solaire equipe.",
        "capacity_l": 300,
        "sale_price": 9800,
        "unit": "piece",
    },
    {
        "reference": "COL-2M",
        "category": "thermal",
        "subcategory": "capteur",
        "brand": "HeliAntha Therm",
        "model": "Capteur 2 m2",
        "description": "Capteur solaire thermique plan.",
        "sale_price": 2600,
        "unit": "piece",
        "technical_specs": {"surface_m2": 2},
    },
    {
        "reference": "HEL-INVT-2R2-MONO",
        "category": "drives",
        "subcategory": "monophase",
        "brand": "INVT",
        "model": "2.2 kW mono",
        "description": "Variateur de pompage de test monophase.",
        "power_kw": 2.2,
        "sale_price": 1800,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 2.2, "phases": "monophase"},
        "demo": False,
    },
    {
        "reference": "SI23-D5-5R5",
        "category": "drives",
        "subcategory": "triphase",
        "brand": "VEICHI",
        "model": "5.5 kW tri",
        "description": "Variateur de pompage de test triphase.",
        "power_kw": 5.5,
        "sale_price": 2375,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 5.5, "phases": "triphase"},
        "demo": False,
    },
    {
        "reference": "SI23-D5-7R5",
        "category": "drives",
        "subcategory": "triphase",
        "brand": "VEICHI",
        "model": "7.5 kW tri",
        "description": "Variateur de pompage de test triphase.",
        "power_kw": 7.5,
        "sale_price": 2875,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 7.5, "phases": "triphase"},
        "demo": False,
    },
    {
        "reference": "SI23-D5-011",
        "category": "drives",
        "subcategory": "triphase",
        "brand": "VEICHI",
        "model": "11 kW tri",
        "description": "Variateur de pompage de test triphase.",
        "power_kw": 11,
        "sale_price": 3583.33,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 11, "phases": "triphase"},
        "demo": False,
    },
    {
        "reference": "SI23-T3-015",
        "category": "drives",
        "subcategory": "triphase",
        "brand": "VEICHI",
        "model": "15 kW tri",
        "description": "Variateur de pompage de test triphase.",
        "power_kw": 15,
        "sale_price": 4583.33,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 15, "phases": "triphase"},
        "demo": False,
    },
    {
        "reference": "SI23-T3-018",
        "category": "drives",
        "subcategory": "triphase",
        "brand": "VEICHI",
        "model": "18 kW tri",
        "description": "Variateur de pompage de test triphase.",
        "power_kw": 18,
        "sale_price": 5625,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 18, "phases": "triphase"},
        "demo": False,
    },
    {
        "reference": "SI23-T3-030",
        "category": "drives",
        "subcategory": "triphase",
        "brand": "VEICHI",
        "model": "30 kW tri",
        "description": "Variateur de pompage de test triphase.",
        "power_kw": 30,
        "sale_price": 8250,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 30, "phases": "triphase"},
        "demo": False,
    },
    {
        "reference": "SI23-T3-037",
        "category": "drives",
        "subcategory": "triphase",
        "brand": "VEICHI",
        "model": "37 kW tri",
        "description": "Variateur de pompage de test triphase.",
        "power_kw": 37,
        "sale_price": 11791.67,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 37, "phases": "triphase"},
        "demo": False,
    },
    {
        "reference": "SI23-T3-045",
        "category": "drives",
        "subcategory": "triphase",
        "brand": "VEICHI",
        "model": "45 kW tri",
        "description": "Variateur de pompage de test triphase.",
        "power_kw": 45,
        "sale_price": 16050,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 45, "phases": "triphase"},
        "demo": False,
    },
    {
        "reference": "TEST-JA-400-M",
        "category": "panels",
        "subcategory": "test",
        "brand": "JA Solar",
        "model": "400-M",
        "description": "Panneau photovoltaique de test 400 W.",
        "power_w": 400,
        "sale_price": 1998.75,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 400},
        "demo": False,
    },
    {
        "reference": "CS6W-590TB-AG",
        "category": "panels",
        "subcategory": "test",
        "brand": "Canadian Solar",
        "model": "TOPBiHiKu6",
        "description": "Panneau photovoltaique de test 590 W.",
        "power_w": 590,
        "sale_price": 1135.2,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 590},
        "demo": False,
    },
    {
        "reference": "TEST-CS-715",
        "category": "panels",
        "subcategory": "test",
        "brand": "Canadian Solar",
        "model": "715W N-Type / TOPCon",
        "description": "Panneau photovoltaique de test 715 W.",
        "power_w": 715,
        "sale_price": 1067.18,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 715},
        "demo": False,
    },
]

for _catalog_product in CATALOG_PRODUCTS:
    _catalog_product.setdefault("demo", True)
    _catalog_product.setdefault("active", 1)
    _catalog_product.setdefault("preferred", False)
    _catalog_product.setdefault("priority", 0)
    _catalog_product.setdefault("currency", "DH")
    _catalog_product.setdefault("vat_rate", 0.20)
