"""Bundled defaults for HeliAntha Smart Quote."""

from .pump_catalog_data import PUMP_CATALOG_DATA

PROJECT_LABELS = {
    "pumping": "Pompage solaire",
    "photovoltaic": "Réduire ma consommation",
    "hybrid": "Solaire hybride avec stockage",
}
PUBLIC_PROJECTS = ("pumping", "photovoltaic", "hybrid")
DASHBOARD_PROJECT_LABELS = {
    "pumping": "Pompage solaire",
    "photovoltaic": "On-Grid",
    "hybrid": "Hybride lithium",
}

QUOTE_STATUSES = [
    "Nouveau",
    "A contacter",
    "Contacte",
    "Etude",
    "Visite programmee",
    "Devis prepare",
    "Devis envoye",
    "Accepte",
    "Refuse",
    "Installation",
    "Termine",
]

CALCULATOR_VERSIONS = {
    "SolarCalculator": "1.0",
    "PumpCalculator": "1.0",
    "OnGridCalculator": "1.0",
    "HybridCalculator": "1.0",
    "PricingEngine": "2.0-bom",
    "ProductSelector": "1.0",
    "CompatibilityChecker": "3.0",
    "BOMBuilder": "1.0",
}

TECHNICAL_REFERENCE = {
    "name": "POMPAGE-HELIANTHA-2026",
    "version": "1.0",
    "description": "Referentiel actif pompage solaire et on-grid.",
    "effective_date": "2026-08-26",
    "status": "Actif",
    "notes": "Les autres parcours restent en reconstruction.",
}

ONGRID_PARAMETER_DEFAULTS = [
    ("protection_acdc_per_pv", "Protection AC/DC par panneau", 130.00, "DH/panneau", "Forfait protection AC/DC par panneau."),
    ("cablage_acdc_per_pv", "Cablage AC/DC par panneau", 80.00, "DH/panneau", "Forfait cablage AC/DC par panneau."),
    ("installation_per_pv", "Installation par panneau", 200.00, "DH/panneau", "Forfait pose et mise en service par panneau."),
    ("transport_per_pv", "Transport par panneau", 50.00, "DH/panneau", "Forfait transport par panneau."),
    ("injection_limit_mono", "Limiteur injection monophase", 2000.00, "DH", "Forfait limiteur d'injection monophase."),
    ("injection_limit_tri_threshold", "Seuil limiteur triphase", 20.00, "kW", "Seuil de puissance DC pour le forfait triphase."),
    ("injection_limit_tri_low", "Limiteur injection triphase bas", 3000.00, "DH", "Forfait triphase jusqu'au seuil inclus."),
    ("injection_limit_tri_high", "Limiteur injection triphase haut", 7000.00, "DH", "Forfait triphase au-dessus du seuil."),
    ("vat_pv_rate", "TVA panneaux", 10.00, "%", "TVA appliquee aux panneaux photovoltaïques."),
    ("vat_transport_rate", "TVA transport", 10.00, "%", "TVA appliquee au transport."),
    ("vat_standard_rate", "TVA standard", 20.00, "%", "TVA appliquee aux autres postes On-Grid."),
    ("psh_hours", "PSH fixe On-Grid", 5.00, "h", "Heures solaires fixes admin, sans ville ni meteo."),
]

COMPANY_SETTINGS = [
    ("company_name", "HELIANTHA", "general", "Nom entreprise"),
    ("phone", "05 30 13 35 83", "contact", "Telephone fixe"),
    ("whatsapp", "+212 661-575128", "contact", "WhatsApp"),
    ("whatsapp_gateway_url", "http://127.0.0.1:3001/send-message", "contact", "WhatsApp - URL passerelle locale"),
    ("admin_whatsapp", "0684056613", "contact", "WhatsApp - Telephone admin"),
    ("app_base_url", "https://devis.heliantha.ma", "contact", "URL publique des devis"),
    ("email", "contact@heliantha.ma", "contact", "E-mail"),
    ("city", "", "contact", "Ville"),
    ("address", "Maroc", "contact", "Adresse"),
    ("website", "www.heliantha.ma", "contact", "Site internet"),
    ("location_url", "https://maps.app.goo.gl/xAfGJugGUMye8oSX7", "contact", "Localisation Google Maps"),
    ("currency", "DH", "quote", "Devise"),
    ("pdf_bank_name", "CIH Bank", "quote", "PDF - Banque"),
    ("pdf_rib", "A renseigner", "quote", "PDF - RIB"),
    ("pdf_iban", "A renseigner", "quote", "IBAN"),
    ("pdf_contact_name", "Dr. Omar EL KADMIRI", "quote", "PDF - Interlocuteur"),
    ("pdf_social_links", "LinkedIn, Instagram (@helianthamorocco), Facebook, YouTube, TikTok (@heliantha_solar)", "quote", "PDF - Reseaux sociaux"),
    ("pdf_legal_footer", "R.C. : 34905 - Patente : 29404580 - I.F. : 25046659 - C.N.S.S. : 574789 - ICE : 002035491000003", "quote", "PDF - Mentions legales"),
]

CALCULATION_PARAMETERS = []
PRICING_RULES = []
PARAMETER_PRESENTATION = {}
PARAMETER_CLASSIFICATION = {}
PARAMETER_ENGINE_USAGE = {}
CATEGORY_PRESENTATION = {}

SOURCE_TYPES = {
    "demo": {"label": "HeliAntha", "badge": "HeliAntha", "description": "Valeur HeliAntha utilisee pour les simulations."},
    "heliantha": {"label": "HeliAntha", "badge": "HeliAntha", "description": "Valeur validee par HeliAntha."},
    "manufacturer": {"label": "Fabricant", "badge": "Fabricant", "description": "Donnee issue d'une fiche technique constructeur."},
    "reference": {"label": "Referentiel", "badge": "Referentiel", "description": "Donnee issue d'un referentiel technique."},
    "physical_constant": {"label": "Constante physique", "badge": "Constante", "description": "Valeur scientifique geree dans le code."},
    "catalog": {"label": "Catalogue", "badge": "Catalogue", "description": "Produit issu du catalogue actif."},
}

CATALOG_PRODUCTS = [
    {
        "reference": "TEST-JA-400-M",
        "category": "panels",
        "subcategory": "test",
        "brand": "JA Solar",
        "model": "400-M",
        "description": "Panneau photovoltaique de test 400 W.",
        "power_w": 400,
        "sale_price": 1998.75,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 400},
        "demo": False,
    },
    {
        "reference": "CS6W-590TB-AG",
        "category": "panels",
        "subcategory": "test",
        "brand": "Canadian Solar",
        "model": "TOPBiHiKu6",
        "description": "Panneau photovoltaique de test 590 W.",
        "power_w": 590,
        "sale_price": 1135.2,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 590},
        "demo": False,
    },
    {
        "reference": "TEST-CS-715",
        "category": "panels",
        "subcategory": "test",
        "brand": "Canadian Solar",
        "model": "715W N-Type / TOPCon",
        "description": "Panneau photovoltaique de test 715 W.",
        "power_w": 715,
        "sale_price": 1067.18,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 715},
        "demo": False,
    },
    {
        "reference": "ONGRID-PV-400",
        "category": "panels",
        "subcategory": "ongrid",
        "brand": "HeliAntha",
        "model": "400 W",
        "description": "Panneau photovoltaïque On-Grid 400 W.",
        "power_w": 400,
        "sale_price": 480.00,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 400},
        "demo": False,
        "preferred": True,
        "priority": 20,
    },
    {
        "reference": "ONGRID-PV-590",
        "category": "panels",
        "subcategory": "ongrid",
        "brand": "HeliAntha",
        "model": "590 W",
        "description": "Panneau photovoltaïque On-Grid 590 W.",
        "power_w": 590,
        "sale_price": 480.00,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 590},
        "demo": False,
        "preferred": True,
        "priority": 20,
    },
    {
        "reference": "ONGRID-PV-630",
        "category": "panels",
        "subcategory": "ongrid",
        "brand": "HeliAntha",
        "model": "630 W",
        "description": "Panneau photovoltaïque On-Grid 630 W.",
        "power_w": 630,
        "sale_price": 520.00,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 630},
        "demo": False,
        "preferred": True,
        "priority": 20,
    },
    {
        "reference": "ONGRID-PV-715",
        "category": "panels",
        "subcategory": "ongrid",
        "brand": "HeliAntha",
        "model": "715 W",
        "description": "Panneau photovoltaïque On-Grid 715 W.",
        "power_w": 715,
        "sale_price": 580.00,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 715},
        "demo": False,
        "preferred": True,
        "priority": 20,
    },
    {
        "reference": "HYB-PV-585",
        "category": "panels",
        "subcategory": "hybrid",
        "brand": "HeliAntha",
        "model": "585 W bifacial",
        "description": "Panneau photovoltaïque hybride 585 W mono / bi-facial.",
        "power_w": 585,
        "sale_price": 480.00,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 585},
        "demo": False,
        "preferred": True,
        "priority": 30,
    },
    {
        "reference": "HYB-PV-725",
        "category": "panels",
        "subcategory": "hybrid",
        "brand": "HeliAntha",
        "model": "725 W",
        "description": "Panneau photovoltaïque hybride 725 W.",
        "power_w": 725,
        "sale_price": 600.00,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 725},
        "demo": False,
        "preferred": True,
        "priority": 30,
    },
    {
        "reference": "HYB-PV-720",
        "category": "panels",
        "subcategory": "hybrid",
        "brand": "HeliAntha",
        "model": "720 W",
        "description": "Panneau photovoltaïque hybride 720 W fallback.",
        "power_w": 720,
        "sale_price": 590.00,
        "stock": 200,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.10,
        "technical_specs": {"power_w": 720},
        "demo": False,
        "preferred": True,
        "priority": 20,
    },
    {
        "reference": "ONGRID-STRUCTURE-PV",
        "category": "structures",
        "subcategory": "ongrid",
        "brand": "HeliAntha",
        "model": "Structure PV",
        "description": "Structure photovoltaïque On-Grid par panneau.",
        "sale_price": 200.00,
        "stock": 500,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"structure_type": "pv"},
        "demo": False,
        "preferred": True,
        "priority": 20,
    },
    {
        "reference": "BAT-DEYE-5KWH",
        "category": "batteries",
        "subcategory": "lithium",
        "brand": "Deye/HeliAntha",
        "model": "5 kWh 51.2 V",
        "description": "Batterie Lithium Deye/HeliAntha 5 kWh 48V/51.2V.",
        "capacity_kwh": 5,
        "purchase_price": 11000,
        "sale_price": 13500,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"capacity_kwh": 5, "nominal_voltage_v": 51.2, "technology": "lithium", "continuous_power_kw": 5, "parallel_max": 16},
        "demo": False,
        "preferred": True,
        "priority": 30,
    },
    {
        "reference": "BAT-DEYE-15KWH",
        "category": "batteries",
        "subcategory": "lithium",
        "brand": "Deye/HeliAntha",
        "model": "15 kWh 51.2 V",
        "description": "Batterie Lithium Deye/HeliAntha 15 kWh 51.2V.",
        "capacity_kwh": 15,
        "purchase_price": 30000,
        "sale_price": 36000,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"capacity_kwh": 15, "nominal_voltage_v": 51.2, "technology": "lithium", "continuous_power_kw": 10, "parallel_max": 16},
        "demo": False,
        "preferred": True,
        "priority": 30,
    },
    {
        "reference": "DEYE-SUN-6K-SG03LP1-EU",
        "category": "inverters",
        "subcategory": "hybrid",
        "brand": "Deye",
        "model": "SUN-6K-SG03LP1-EU",
        "description": "Onduleur hybride Deye 6 kW monophasé.",
        "power_kw": 6,
        "purchase_price": 9500,
        "sale_price": 12000,
        "stock": 10,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 6, "phases": "monophase", "type": "hybrid", "battery_compatible": True, "nominal_battery_voltage_v": 51.2},
        "demo": False,
        "preferred": True,
        "priority": 40,
    },
    {
        "reference": "DEYE-SUN-10K-SG02LP1-EU",
        "category": "inverters",
        "subcategory": "hybrid",
        "brand": "Deye",
        "model": "SUN-10K-SG02LP1-EU",
        "description": "Onduleur hybride Deye 10 kW monophasé.",
        "power_kw": 10,
        "purchase_price": 13500,
        "sale_price": 17000,
        "stock": 10,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 10, "phases": "monophase", "type": "hybrid", "battery_compatible": True, "nominal_battery_voltage_v": 51.2},
        "demo": False,
        "preferred": True,
        "priority": 40,
    },
    {
        "reference": "DEYE-SUN-18K-SG01LP1-EU",
        "category": "inverters",
        "subcategory": "hybrid",
        "brand": "Deye",
        "model": "SUN-18K-SG01LP1-EU",
        "description": "Onduleur hybride Deye 18 kW monophasé.",
        "power_kw": 18,
        "purchase_price": 22000,
        "sale_price": 28000,
        "stock": 10,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 18, "phases": "monophase", "type": "hybrid", "battery_compatible": True, "nominal_battery_voltage_v": 51.2},
        "demo": False,
        "preferred": True,
        "priority": 40,
    },
    {
        "reference": "HEL-INVT-2R2-MONO",
        "category": "drives",
        "subcategory": "monophase",
        "brand": "INVT",
        "model": "2.2 kW mono",
        "description": "Variateur de pompage monophase.",
        "power_kw": 2.2,
        "sale_price": 1800,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 2.2, "phases": "monophase"},
        "demo": False,
    },
    {
        "reference": "HEL-INVT-2R2-TRI",
        "category": "drives",
        "subcategory": "triphase",
        "brand": "INVT",
        "model": "2.2 kW tri",
        "description": "Variateur de pompage triphase.",
        "power_kw": 2.2,
        "sale_price": 1900,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": 2.2, "phases": "triphase", "voltage_v": 380},
        "demo": False,
    },
]

for reference, power_kw, sale_price in [
    ("SI23-D5-5R5", 5.5, 2375),
    ("SI23-D5-7R5", 7.5, 2875),
    ("SI23-D5-011", 11, 3583.33),
    ("SI23-T3-015", 15, 4583.33),
    ("SI23-T3-018", 18, 5625),
    ("SI23-T3-030", 30, 8250),
    ("SI23-T3-037", 37, 11791.67),
    ("SI23-T3-045", 45, 16050),
]:
    CATALOG_PRODUCTS.append({
        "reference": reference,
        "category": "drives",
        "subcategory": "triphase",
        "brand": "VEICHI",
        "model": f"{power_kw:g} kW tri",
        "description": "Variateur de pompage triphase.",
        "power_kw": power_kw,
        "sale_price": sale_price,
        "stock": 20,
        "unit": "piece",
        "warranty": "A confirmer",
        "vat_rate": 0.20,
        "technical_specs": {"power_kw": power_kw, "phases": "triphase"},
        "demo": False,
    })

for inverter_brand, brand_priority in (("Deye", 30), ("SolaX", 20)):
    for phase, entries in {
        "monophase": [
            (3, 6000),
            (5, 7500),
            (6, 8500),
            (8, 10500),
            (10, 12500),
            (12, 14500),
            (15, 17500),
        ],
        "triphase": [
            (6, 9500),
            (8, 11500),
            (10, 13500),
            (15, 18000),
            (20, 24000),
            (30, 36000),
            (50, 62000),
            (100, 118000),
        ],
    }.items():
        phase_label = "mono" if phase == "monophase" else "tri"
        brand_ref = inverter_brand.upper()
        for power_kw, sale_price in entries:
            CATALOG_PRODUCTS.append({
                "reference": f"{brand_ref}-{phase_label.upper()}-{str(power_kw).replace('.', 'R')}KW",
                "category": "inverters",
                "subcategory": phase,
                "brand": inverter_brand,
                "model": f"{power_kw:g} kW {phase_label}",
                "description": f"Onduleur réseau {inverter_brand} On-Grid.",
                "power_kw": power_kw,
                "sale_price": sale_price,
                "stock": 10,
                "unit": "piece",
                "warranty": "A confirmer",
                "vat_rate": 0.20,
                "technical_specs": {"power_kw": power_kw, "phases": phase, "type": "on_grid"},
                "demo": False,
                "preferred": True,
                "priority": brand_priority,
            })

CATALOG_PRODUCTS.extend([
    {
        "reference": pump["stable_key"],
        "category": "pumps",
        "subcategory": "immergee",
        "brand": pump["brand"],
        "model": pump["source_model"],
        "description": f"Pompe solaire {pump['power_hp']:g} CV",
        "power_kw": pump["power_kw"],
        "voltage": pump["voltage"],
        "current_amp": pump["current_amp"],
        "sale_price": pump["sale_price_source"],
        "unit": "piece",
        "vat_rate": None,
        "demo": False,
        "technical_specs": {
            "power_hp": pump["power_hp"],
            "power_kw": pump["power_kw"],
            "outlet_diameter": pump["outlet_diameter"],
            "voltage_v": pump["voltage"],
            "current_a": pump["current_amp"],
            "price_tax_basis": pump["price_tax_basis"],
            "source_model": pump["source_model"],
        },
        "pump_curve_points": pump["curve_points"],
    }
    for pump in PUMP_CATALOG_DATA
])

for _catalog_product in CATALOG_PRODUCTS:
    _catalog_product.setdefault("demo", True)
    _catalog_product.setdefault("active", 1)
    _catalog_product.setdefault("preferred", False)
    _catalog_product.setdefault("priority", 0)
    _catalog_product.setdefault("currency", "DH")
    _catalog_product.setdefault("vat_rate", 0.20)
